version: '3'

services:
  rms_context_service:
    image: rms_context_image:latest
    container_name: rms_context
    volumes:
      - .:/rms_context_volume
    ports:
      - "8000:8000"
    restart: always
    build: .