version: '3'

services:
  rms_context_service:
    image: rms_context_image:latest
    container_name: rms_context
    volumes:
      - .:/rms_context_volume
    ports:
      - "8000:8000"
    restart: always
    build: .
    # command: bash -c "source venv/bin/activate && python3 manage.py runserver 0.0.0.0:8000"
    networks:
      rms_network:
          ipv4_address:  172.18.0.2

networks:
  rms_network:
    external: true