version: '3'

services:
  rms_context_service:
    image: rms_context_image:latest
    container_name: rms_context_container
    volumes:
      - .:/rms_context_volume
    ports:
      - "8001:8001"
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    networks:
      rms_network:
          ipv4_address:  192.168.16.2

networks:
  rms_network:
    external: true