# Generated by Django 3.0.3 on 2020-04-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('name', 'application', 'parent')},
        ),
    ]
