# Generated by Django 3.0.3 on 2020-05-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='route_front',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='entities.RoutesFront'),
        ),
    ]
