# Generated by Django 3.0.3 on 2020-07-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='service_route',
            new_name='service_routes',
        ),
    ]
