# Generated by Django 3.0.3 on 2020-04-11 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_sessions', to='entities.Client'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usersession',
            unique_together={('user', 'application', 'client')},
        ),
    ]
