# Generated by Django 3.0.3 on 2020-04-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20200412_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='front_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='front_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
