# Generated by Django 3.0.3 on 2020-07-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20200711_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='groups', to='entities.Module'),
        ),
    ]
