# Generated by Django 3.0.3 on 2020-07-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_group_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='entities.ServiceRoute'),
        ),
    ]
