# Generated by Django 3.0.3 on 2020-07-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_module_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='entities.ServiceRoute'),
        ),
    ]
