# Generated by Django 3.0.3 on 2020-04-14 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_auto_20200414_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endpoints', to='entities.Module'),
        ),
    ]
