# Generated by Django 3.0.3 on 2020-04-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_auto_20200414_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='valid_until',
            field=models.DateField(),
        ),
    ]
